### ISSUE TITLE
Button set look is broken on Google Chrome 31.x for Mac

### ISSUE THREAD

**Issue by andrematos** [jquery-ui-bootstrap/jquery-ui-bootstrap#222]
It seems that right after Google Chrome got updated from 30.x to 31.x on my Mac, the Button Set is displayed each one below the other instead of side by side (see screenshot):

![screen shot 2013-11-13 at 7 50 42 pm](https://f.cloud.github.com/assets/4837992/1537488/23a8bd0a-4cc7-11e3-8f47-01fe67b349dc.png)

Is this an issue with the latest Google Chrome update or is with the jquery-ui-bootstrap?

I have noticed same behaviour when using Google Chrome Canary (33.x) for Mac.

**Comment by dharapvj** [comment]
... Can this be the issue? https://github.com/twbs/bootstrap/issues/9282

**Comment by mleden** [comment]
I don't believe that this is Mac-specific either.  
My client stack is this:
Windows 7
jQuery
jQuery UI Bootstrap
Immediately upon upgrading Chrome from 30.x to 31.x, I started seeing the problem identified by OP, i.e., the buttons in my buttonset are "stacked" instead of aligned horizontally.
Firefox v17.0.10 continues to render the buttons aligned horizontally, i.e., "correctly".

**Comment by corydorning** [comment]
This is occurring in Chrome 31 on Windows XP. It isn't just a bootstrap thing. I'm using jQuery UI. Just commenting because i found this issue while doing a google search.

**Comment by borski** [comment]
I can verify this is happening too. Any workaround?

**Comment by andrematos** [comment]
I believe the problem might be somewhere in the query-ui-bootstrap lib because I don't see the problem happening at the getbootstrap.com page (http://getbootstrap.com/2.3.2/components.html#buttonGroups), neither at the jQuery page (http://jqueryui.com/button/#radio).
