### ISSUE TITLE
Tabs CSS like in boostrap, file input

### ISSUE THREAD

**Issue by LKay** [jquery-ui-bootstrap/jquery-ui-bootstrap#27]
Fix CSS for jQui tabs so they would look like bootstrap's ones. The grey hover and font color and spaces between tabs etc. 

Another thing , maybe you could make bootstrap like styling for file input using http://www.filamentgroup.com/lab/jquery_custom_file_input_book_designing_with_progressive_enhancement/ ?

**Comment by addyosmani** [comment]
Completely agree with this. I'll add improved hover states and spacing to the tabs this week. 

With respect to the bootstrap like styling for file inputs, I think it's an interesting idea. I hadn't considered it as yet, but I don't think it would be that hard to do. Could you possibly post about the file inputs in a separate issue so that both of these requests can be handled independently?

Cheers! :)

**Comment by kbsali** [comment]
BTW : the Jquery-UI-Tabs' css makes bootstrap's tabs NOT to work!

Any reason why we should have both?
