### ISSUE TITLE
More cool features

### ISSUE THREAD

**Issue by panosru** [jquery-ui-bootstrap/jquery-ui-bootstrap#32]
I love Twitter bootstrap and I love jQuery and jQuery UI so this means that I love jQuery UI Bootstrap theme and so do many people.

A request was made previously for adding custom input type fields and I loved the idea, now I believe there are more things that could be made for example [plupload](http://www.plupload.com/) integration,  [chosen](http://harvesthq.github.com/chosen/), [multiselect](http://quasipartikel.at/multiselect/) and others...

Tools like these are used in almost every web app and I believe they are very useful specially if they are all integrated in a nice ui like twitter bootstrap.

_although chosen has already great UI it could be improved even more I believe ;)_

**Comment by panosru** [comment]
I started working on plupload I can't promise when it will be ready because I'm a bit busy :/ but here is a preview on how it is so far (still long way to go :) )

![plupload jquery ui bootstrap](http://dl.dropbox.com/u/16165490/Screenshots/jquery-ui-bootstrap-plupload.png)

**Comment by addyosmani** [comment]
@panosru Given that you've started working on some of these, I think it would be useful to share my roadmap for how I plan to tackle third party components :)
- We want to ensure where possible we are only overriding/replacing the theme for components (rather than changing the JS/jQuery for the plugins at all). This will allow people to just drop in the latest version of the plugin from upstream and the theme will just work with it.
- We're going to start separating out the third-party examples into separate pages for previews. The reason for this is that there's currently a lot of third-party JS currently being loaded into the demo page and it's affecting the perception of how quickly everything renders (which is relatively quick when we're just talking about core jQuery UI stuff)
- The project targets stable FF, Chrome, Safari, Opera and IE8+. Whilst I know that developers supporting modern browsers would like to just IE9/10, this solution is targeted at both them and those like me that work in enterprise where IE8 is the baseline right now (fwiw, I also test in older versions of IE but issues there tend to be patchwelcome)

Hope that helps!

**Comment by panosru** [comment]
@addyosmani Thanks for sharing your roadmap :)
1. Yes as you said, when possible overriding/replacing the theme for components would be the best way to go instead of modifying the js/jq code of plugins, but as I said in previous issue, some times it's not possible to do it or even if it will be possible it won't be as good as it would and in my way of thinking is _if you want to deliver something which won't be good then don't deliver it at all_. We are an open source community and there are many people with knowledge out there so I don't believe you have to worry about supporting 3rd party plugins, besides, when something works and it works good you will update it only when it really need to be updated because of either security reason or compatibility reason everything else are optional. 
2. Separating 3rd party examples in order to not have a "monster page" would be good too but for now I think it is ok in the way it is.
3. Targeting stable release of browsers of course is out of the question it is the main goal. I will give my personal opinion regarding IE and I'm sure others will agree and others not. Personally I don't support IE8 (why to do so? MS don't support it, I mean it support IE8 because windows XP users use it but they stopped support for windows XP so supporting a browser that lives only because on an unsupported OS is a joke in my opinion) I know that in enterprise level you may have a client that demands support for IE6 well since we spoke about enterprise I either reject that client or charge him lot more for support of IE6/7/8, usually I do the second option :) . Now regarding this project, jQuery, jQuery UI, Twitter Bootstrap, jQuery UI Bootstrap theme... all those things together I believe won't be useful for a web-site it would be used for web-apps and when we talk about web-apps we can add some requirements too, for instance when I create a CMS for a client I have some requirements for it... of course I will make sure his website will work for IE7/8/9 etc but his back-end will have requirements in order to work properly. 

Well I have to go now but this is my opinion.

**Comment by addyosmani** [comment]
@panosru No worries. Thanks again for your input. I agree that there are cases where some plugins actually heavily make use of custom application of css classes to components in order to theme them and it's occasionally not possible for us to use CSS alone to solve this problem. I'm going to look some more at the additions you've been working on today. As I've mentioned, they'll probably land with a little bit of cleanup :)

**Comment by panosru** [comment]
For those who are wondering how plupload  progress goes, I have to admit that I took a decision to not create a theme for twitter bootstrap as there are already two great projects that use upload functionality with twitter bootstrap theme. 

The one is [UploadKit](https://github.com/entropillc/UploadKit) and the other is [jQuery File Upload](https://github.com/blueimp/jQuery-File-Upload) 

Use which ever fit's your needs

**Comment by addyosmani** [comment]
@panosru I know you were very helpful with the project a year ago when we first started it out. Would you be interested in getting involved again? We'd love to pick it back up and get compatibility with the latest Bootstrap.
