### ISSUE TITLE
Wijmo Menu Text Inputs Box Shadow

### ISSUE THREAD

**Issue by Francisc** [jquery-ui-bootstrap/jquery-ui-bootstrap#51]
This isn't a bug, but I would remove the bottom box-shadow from the text inputs in the wijmo menu.
It makes no sense there, nothing else has shadows.
Plus, when getting focus, it looks like the box is moving and growing a little.

What do you think?

**Comment by addyosmani** [comment]
Thanks for the feedback @Francisc. For the moment I'd like us to hold off on any Wijmo-specific changes as the team over at Wijmo are currently working on bringing improved support (both visually and otherwise) to the theme for their widgets. Happy to consider other visual improvements on what they submit when it comes over :)

**Comment by Francisc** [comment]
Ah, OK. Thanks.
