### ISSUE TITLE
Discussion: Bootstrap 1.0 or shift to 2.0 (once final)

### ISSUE THREAD

**Issue by addyosmani** [jquery-ui-bootstrap/jquery-ui-bootstrap#52]
I've just been reviewing Twitter Bootstrap 2.0 WIP and it introduces both a large number of new visual components and quite a shift in the visual appearance of the project since 1.0. At the request of the Bootstrap team, the WIP isn't being put up anywhere live pre-release but if you'd like to review it, you can grab 2.0 WIP here: https://github.com/twitter/bootstrap/tree/2.0-wip

This raises some interesting questions about how jQuery UI Bootstrap should proceed:
- Should we stick with version 1.0 of Bootstrap and continue improving support for it as well as theming more plugins? (this would effectively mean we're providing a 'Bootstrap' jQuery UI theme, but not supporting Twitter Bootstrap (latest). Arguments for: the current theme is visually pleasing and our time could be spent improving support for more third party plugins if we stayed this course. There is a need for a stable, modern theme in the community.
- Should we move to Bootstrap 2.0 (once final)? This will involve a very large amount of work. a) We'll have to retheme the existing components, b)  extend our support to cover more 'modes' that can be customized using jQuery UI which are being included by default in Bootstrap 2.0 and c) cover support for plugins/otherwise that can match as much as possible 2.0. Arguments for: this will improve the overall visuals the theme offers, developers will be able to continue to use Bootstrap.latest and jQuery UI.latest together.

**Could I have a show of votes? +1 to upgrade to 2.0, -1 to stick with 1.0 and do our own thing.**

Happy to also hear further input from others about their thoughts on the above.

**Comment by pusewicz** [comment]
+1

**Comment by emincansumer** [comment]
+1

**Comment by rollsappletree** [comment]
+1

**Comment by dciccale** [comment]
+1

**Comment by bennyschudel** [comment]
+1

**Comment by JamesMGreene** [comment]
+1

Though you should probably leave a cut of 1.0 available for download.

**Comment by jlnslv** [comment]
+1

**Comment by MadeMyDay** [comment]
+1

**Comment by tud** [comment]
+1

**Comment by johnmichel** [comment]
+1

**Comment by patik** [comment]
+1

**Comment by nexeck** [comment]
+1

**Comment by ddprrt** [comment]
+1

**Comment by iknite** [comment]
+1

**Comment by davej** [comment]
+1

**Comment by qwertypants** [comment]
+1

**Comment by Francisc** [comment]
+1

**Comment by rubysolo** [comment]
+1

**Comment by kshwetabh** [comment]
+1

**Comment by daFish** [comment]
+1

**Comment by Gavrisimo** [comment]
+1

**Comment by WaYdotNET** [comment]
+1

**Comment by huzzi** [comment]
+1

**Comment by master-lincoln** [comment]
+1

**Comment by neilholcomb** [comment]
+1

**Comment by kriserickson** [comment]
+1

**Comment by paglias** [comment]
+1

**Comment by sindresorhus** [comment]
:+1:

**Comment by studioromeo** [comment]
@sindresorhus how on earth did you do that?!

+1 although if you like 1.0 then theres no harm in sticking with that I guess

**Comment by paglias** [comment]
using this code  ````
:+1:

```
```

**Comment by jerriep** [comment]
+1

**Comment by sindresorhus** [comment]
@studioromeo GitHub :octocat: has [emoji support](http://www.emoji-cheat-sheet.com/) :muscle:

**Comment by robrbecker** [comment]
+1

**Comment by screenm0nkey** [comment]
:thumbsup:

**Comment by rakeshtembhurne** [comment]
+1

**Comment by svnlto** [comment]
:whale:

**Comment by jlsync** [comment]
+1

**Comment by lightglitch** [comment]
+1

**Comment by Hquant** [comment]
+1

**Comment by euge** [comment]
+1

**Comment by jaimesuez** [comment]
+1

**Comment by clannadsystems** [comment]
+1 coz i need to play with new features now and i couldnt wait.

**Comment by nfaiz** [comment]
+1

**Comment by vierbergenlars** [comment]
:+1:

**Comment by lrodziewicz** [comment]
+1

**Comment by housekeeper** [comment]
+1

**Comment by mbarbieri** [comment]
+1

**Comment by sumityadav** [comment]
+1

**Comment by jensenkd** [comment]
+1

**Comment by ecaldwell** [comment]
+1

**Comment by ajrkerr** [comment]
+1

**Comment by zowber** [comment]
+1

**Comment by marcuspocus** [comment]
+1

**Comment by ghost** [comment]
:+1:

**Comment by changtimwu** [comment]
+1

**Comment by felixgogo** [comment]
+1

**Comment by yorktsai** [comment]
+1

**Comment by beata** [comment]
+1

**Comment by diimpp** [comment]
+1

**Comment by jahvi** [comment]
:+1:

**Comment by alien3d** [comment]
+1

**Comment by gpetrov** [comment]
+1 and Bootstrap 2.0 is final now

**Comment by RyanxHuang** [comment]
++1

**Comment by havvg** [comment]
+2.0

**Comment by antage** [comment]
+1

**Comment by robertdean** [comment]
+1

**Comment by panosru** [comment]
+1

**Comment by rdandy** [comment]
+1

**Comment by alexfigueiredo** [comment]
+1

**Comment by mdeltito** [comment]
+1

**Comment by p3drosola** [comment]
+1 

I love the responsive design support.

**Comment by ghost** [comment]
+1

**Comment by bdufresne** [comment]
-1 (just kidding)

**Comment by ghost** [comment]
+1

**Comment by volksman** [comment]
+1

**Comment by nukr** [comment]
+1

**Comment by AlexLittlejohn** [comment]
:+1:

**Comment by panosru** [comment]
@addyosmani I did some briefly integration of jquery ui bootstrap with bootstrap 2 but I didn't changed the custom jquery ui theme I just added bootstrap 2 css and js... 

The big work is to convert old jquery ui theme to look more like bootstrap 2.0 theme.

Maybe I'll work a bit more on that and dedicate some time on it.

The good part also is that now you don't need to hack bootstrap css files because it seems it don't break anything in jquery ui, it was plug-and-play so far with my tests.

You can check a preview [here](http://dl.dropbox.com/u/16165490/jquery-ui-bootstrap/index.html) nothing impressive so far, just playing around... 

EDIT:
@addyosmani maybe jquery ui bootstrap theme should be made with less in order to get bootstrap's variables and use them instead of hard-coding them, this will make the upgrade easier for future changes of bootstrap.

**Comment by ahmdrefat** [comment]
+1

**Comment by kelhusseiny** [comment]
+1

**Comment by dennisoehme** [comment]
+1

**Comment by addyosmani** [comment]
@panosru You raise a very valid point. One of the issues with building the first version was a heavy reliance on custom matching color schemes and where possible, I'd like to avoid this for the next version. I'm not the biggest fan in the world of LESS, but I'll try to experiment with it as an option :) It would definitely make maintaining sync with future versions of Bootstrap a lot easier than it is now. 

You may remember seeing a previous PR with a LESS version of the theme. Given that there are still some components in Bootstrap 2 that haven't hugely changed, do you think it's worth cleaning that up and using it as a base or starting from scratch?

**Comment by panosru** [comment]
@addyosmani Not only it would make maintaining new versions of bootstrap easier but as you noticed bootstrap 2 provides the ability of customization as a result if I customize my version of bootstrap then jquery ui bootstrap theme will adopt on my settings. I'm not really sure about that though because so far from what I noticed is that the customization tool generate's css and not less files, but either-way at least maintaining would be much easier to do.

Yes I remember you talking about Pull #41 by @t1gr0u I did a check again on that and it seems already good to me, I would prefer to start from that instead of from scratch (even if generally I always prefer to do things from scratch) I guess it worth of working on it for bootstrap 2 integration.

Another point I want to mention is that we shouldn't touch bootstrap's code, what I mean is that for instance in jquery ui bootstrap 1 some bootstrap css break some our jquery interface etc so we had to touch bootstrap's [le|c]ss files, I would suggest instead to have a `style.less` which would `@import bootstrap.less` and after that `@import jquery-ui-bootstrap.less` so we could override anything we need from bootstrap without interacting with core files of bootstrap, this will also help us for better maintenance, and better overlook of changes we did. So far that I test bootstrap2 with jquery ui bootstrap seems that bootstrap 2 works fine with jquery ui theme and does not break anything, so no overriding is needed.

**Comment by quangbahoa** [comment]
+1

**Comment by pvulgaris** [comment]
+1

**Comment by t1gr0u** [comment]
hi @panosru, @addyosmani,

let me if I can be any help on the LESS files

**Comment by svnlto** [comment]
This might be a good starting point, only if I'm not missing the point completely :)

https://github.com/svnlto/jQueryUILess

**Comment by panosru** [comment]
@svnlto I prefer to break apart @t1gr0u 's less file since he already added the variables in his less file so it would be much easier :) but this could be a good example on how we should abstract our theme in order to have a better scope of the code :)

**Comment by panosru** [comment]
Also something about +1, I believe no more +1 are needed, we got the point now what is needed is contribution to make it happen :)

**Comment by t1gr0u** [comment]
breaking the files would be good

**Comment by xcambar** [comment]
simply: +1

**Comment by t1gr0u** [comment]
i've broke down the LESS file: https://github.com/t1gr0u/jquery-ui-bootstrap

**Comment by panosru** [comment]
@t1gr0u good work! I like it like that :)

**Comment by t1gr0u** [comment]
it make easier to work on and to update :)

**Comment by svnlto** [comment]
@t1gr0u good work!

**Comment by t1gr0u** [comment]
@panosru , @svnlto thank you :)

**Comment by perucomsultores** [comment]
+1

**Comment by jeremysnyder** [comment]
+1

**Comment by henvic** [comment]
+1

**Comment by addyosmani** [comment]
@panosru Due to the number of votes we're continuing to receive on this and the fact the decision is now unanimous I think I'm going to close this thread and open a new one for 2.0 discussions solely.

**Comment by adityamenon** [comment]
:star::star::star::star::star:

**Comment by hackervera** [comment]
the only octo anything "actual" emoji is :octopus:
