### ISSUE TITLE
conflicts with bootstrap.css

### ISSUE THREAD

**Issue by evoskuil** [jquery-ui-bootstrap/jquery-ui-bootstrap#59]
I've been using jquery-ui-bootstrap with bootstrap.css and have noticed a couple of conflicts which seem unnecessary. For example, jquery-ui-bootstrap styles input[type="text"]. This is of course not a selection unique to jquery-ui, and bootstrap already applies its style to this selector. Conflicts with bootstrap are invited by styling selections that are not unique to jquery-ui. In this case the bootstrap .search-query style is overwritten to no longer have rounded corners, because it's a text input. In patching jquery-ui-bootstrap (to remove all style applied to input[type="text"]) I noticed that there are several applications of style to selections that are not unique to jquery-ui (e.g. textarea, input). I would recommend that these be removed or at least made more selective so that they only apply to jquery-ui components.

**Comment by panosru** [comment]
bootstrap.css file is not related to jQuery UI thus it's styles don't have `.ui-` prefix, of course I can see your point it is somethings that I will try to avoid to be happen in jQuery UI Bootstrap project on next release which will integrate Bootstrap 2 and try to be vendor independent in order to be able to update the project easier. 

For now me and @addyosmani  we focus on getting Bootstrap 2 integrated, once this step is done we will go through all the issues posted on this project.

**Comment by evoskuil** [comment]
Thanks - bootstrap 2 support would be good - especially since I'm already converted to v2 :). I realize that bootstrap is not related to jquery-ui, but my understanding is that jquery-ui-bootstrap aims to make jquery-ui look like bootstrap. In doing so it should really only touch styles that are unique to jquery-ui.

**Comment by panosru** [comment]
jQuery UI **Theme** which is inside jQuery UI **Project** aims to make jQuery UI look like Bootstrap, other than that the project contain the Bootstrap itself along with some extra features which aim to be also Bootstrap-like :)

**Comment by evoskuil** [comment]
I'm sorry, but I'm not following you. This project has the stated goal of providing "a jQuery UI-compatible theme inspired by Bootstrap's design" that can work alongside bootstrap. All I'm suggesting is that, in my opinion, for this goal to be achieved the project should not cause any modifications to controls (like input text) that are not unique to jquery-ui. Otherwise users will have to remove that styling from this theme and hope that doesn't break anything else (which I've already had to do). In any case, thanks for your work on this - it's a really useful project.

**Comment by dirtshoot** [comment]
Any time frame on Bootstrap v2? Just found your project. I was using flckr theme from ui as it is pretty good match with few css overrides...

**Comment by garrettlancaster** [comment]
I agree with evoskull, this project is very useful, but should be providing Bootstrap styling to jquery UI, not altering my other styling (Bootstrap or otherwise).  This is especially annoying since it is overwriting the styling Bootstrap itself provides.  I imagine the primary use case for the project is to be used in conjunction with the Bootstrap framework, and this makes it more difficult.

**Comment by addyosmani** [comment]
@evoskuil If you could point me to a sample of the patched version you've been working on I would be happy to consider revising what jquery-ui-bootstrap does and doesn't override - even happier if it was in the form of a PR.

The challenge remains getting as consistent a visual look as possible when a user does opt to use Bootstrap alongside this project and when they don't. The first version was very much an exercise in getting the look/feel right, but I have no qualms about delaying any further work on the next version in order to provide a release that fixes any styling breakages users aren't expecting. 

@garrettlancaster please feel free to chime in with other examples of what you're experiencing as being unnecessarily altered. Again, I don't mind altering what users consider to be getting overridden unnecessarily but help with this would greatly accelerate the problem getting sorted out.

**Comment by addyosmani** [comment]
If I'm correct we need to remove the following overrides:

```
input, input (of types type text, password, file), textarea
```

This would mean that as a rule of the thumb, the project _must_ remain within the confines of the `.ui` namespace (which I don't really mind). We can work around that.

any others?

**Comment by evoskuil** [comment]
Sorry for the delay. It's been a while since I looked at the specifics, but that sounds correct.
