### ISSUE TITLE
File Input Problems on IE

### ISSUE THREAD

**Issue by bowerm** [jquery-ui-bootstrap/jquery-ui-bootstrap#65]
The File Input does not upload anything when using IE. Tested on IE9.
You can click browse, select a file, and the file name appears in the text part of the control. However when trying to submit/post the form nothing happens.

**Comment by jvosloo** [comment]
Same here

**Comment by jvosloo** [comment]
Anyone?

**Comment by addyosmani** [comment]
Do you have a test case you can post up anywhere that reproduces this issue? The file upload provided is really just the barebones visual component for uploading files and you do need to implement your own backend service for performing the actual file upload. Are you saying the submit isn't actually getting triggered?

**Comment by jvosloo** [comment]
It's hooked up to a Java backend and files upload fine in Google Chrome, Firefox, etc, just not IE9 (I haven't tested older versions of IE yet). I debugged a little and can tell that for some reason the form submit event isn't triggered in IE, unfortunately there's also no errors popping up in the due tools console.   I don't have a test case posted anywhere, since it would require a backend.

**Comment by bowerm** [comment]
We're using an ASP.NET backend, but apart from that I agree with everything Johan said. The problem seems to be that the submit doesn't trigger.

**Comment by MarioBinder** [comment]
same here

**Comment by addyosmani** [comment]
Is anyone able to reproduce this issue using the latest version of the project in master?

**Comment by NeXTs** [comment]
same here
