### ISSUE TITLE
Conflict between JqueryUI buttonset and bootstrap-buttons ?

### ISSUE THREAD

**Issue by syndrael** [jquery-ui-bootstrap/jquery-ui-bootstrap#71]
Hello,
bootstrap-buttons make possible to show a pushed button
JqueryUI make possible aligned buttons in a block.
But i can't do both together, i mean that i'd like a buttonset AND anywhere (outside buttonset) an other button which can be pushed.
If i create a buttonset and i add bootstrap-buttons.js, my buttonset become a radio button block.
And if i don't include bootstrap-buttons.js, my button can't stay pushed.
May you help me ?
Best regards
S.

**Comment by fasouto** [comment]
I had the same issue, it seems like bootstrap and jquery-ui use the same function name and it creates a collision. 
Try to import first jquery-ui and then bootstrap, it worked for me.

**Comment by mhakes** [comment]
Same issue, reordering js or css makes no difference the issue is in the bootstrap.js, it is conflicting with the jq-ui function name.

**Comment by gtraxx** [comment]
Hi, I will rearrange the files and functions to avoid conflicts but only for jQuery UI 1.9.0
I'll make changes quickly ;)

Best regards

**Comment by ryan-mahoney** [comment]
This issue was driving me nuts to identify because I have a rather complex set of Bootstrap/jQuery/other plugins in my project.  From what I can tell, the issue really has nothing to do with this theme, but rather it is a conflict in the bootstrap-button.js portion of the bootstrap.js file and jquery-ui itself.  So one of those projects will need to resolve this matter.
